name: Cypress run
on:
  workflow_dispatch:
env:
  CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
jobs:
  cypress:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-18.17.1-chrome-116.0.5845.187-1-ff-117.0-edge-116.0.1938.76-1
    steps:
      - name: Get project code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i --force
      - name: Run server and test
        run: npm run cy:run:server
      - name: Create report
        if: success() || failure()
        run: npm run report:all
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: mochawesome-report/
  cypress_run2:
    runs-on: ubuntu-latest
    steps:
      - name: Get project code
        uses: actions/checkout@v4

      - name: Install depandencies
        run: npm i --force

      - name: Run server and test
        run: npm run cy:run:server

      - name: Create report
        if: success() || failure()
        run: npm run report:all

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: mochawesome-report/

